#!/usr/bin/env bash
#a Bash script that displays all active IPv4 IPs on the machine is executed on.
#!/usr/bin/env bash
# Displays all acive IPv4 addresses.

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
